export const products = [
  {
    id: 1,
    name: "Celestial Diamond Ring",
    vendor: "Maison Étoile",
    vendorId: 1,
    price: 2450,
    originalPrice: 2800,
    rating: 4.9,
    reviews: 127,
    isNew: true,
    isBestseller: false,
    icon: "💍",
    category: "rings",
    description: "A stunning celestial-inspired diamond ring featuring a brilliant-cut center stone surrounded by a halo of smaller diamonds. The band is crafted from 18k white gold with delicate star engravings.",
    materials: ["18k White Gold", "VS1 Diamonds", "Rhodium Plating"],
    weight: "4.2g",
    images: ["💍", "💎", "✨"],
    inStock: true,
    sku: "CE-DR-001",
  },
  {
    id: 2,
    name: "Pearl Cascade Necklace",
    vendor: "Atelier Perle",
    vendorId: 2,
    price: 1890,
    originalPrice: null,
    rating: 4.8,
    reviews: 89,
    isNew: false,
    isBestseller: true,
    icon: "📿",
    category: "necklaces",
    description: "An elegant cascade of freshwater pearls descending in graduated sizes, connected by 14k gold links. This timeless piece embodies classic sophistication.",
    materials: ["14k Yellow Gold", "AAA Freshwater Pearls"],
    weight: "28g",
    images: ["📿", "🦪", "✨"],
    inStock: true,
    sku: "PC-NE-002",
  },
  {
    id: 3,
    name: "Gold Serpent Bracelet",
    vendor: "Oro Fino",
    vendorId: 3,
    price: 1650,
    originalPrice: null,
    rating: 4.7,
    reviews: 64,
    isNew: false,
    isBestseller: false,
    icon: "🐍",
    category: "bracelets",
    description: "A bold serpent-inspired bracelet handcrafted in solid 18k gold. The intricate scales are individually carved, and emerald eyes add a touch of mystique.",
    materials: ["18k Yellow Gold", "Colombian Emeralds"],
    weight: "35g",
    images: ["🐍", "💛", "✨"],
    inStock: true,
    sku: "GS-BR-003",
  },
  {
    id: 4,
    name: "Sapphire Drop Earrings",
    vendor: "Azure Gems",
    vendorId: 4,
    price: 3200,
    originalPrice: 3600,
    rating: 5.0,
    reviews: 42,
    isNew: true,
    isBestseller: false,
    icon: "💎",
    category: "earrings",
    description: "Exquisite drop earrings featuring natural Ceylon sapphires surrounded by pavé diamonds. Set in platinum for ultimate durability and shine.",
    materials: ["Platinum", "Ceylon Sapphires", "VVS Diamonds"],
    weight: "8.5g",
    images: ["💎", "💙", "✨"],
    inStock: true,
    sku: "SD-EA-004",
  },
  {
    id: 5,
    name: "Vintage Rose Brooch",
    vendor: "Heritage House",
    vendorId: 5,
    price: 980,
    originalPrice: null,
    rating: 4.6,
    reviews: 31,
    isNew: false,
    isBestseller: false,
    icon: "🌹",
    category: "brooches",
    description: "A romantic vintage-inspired rose brooch with hand-painted enamel petals and a ruby center. Each piece is a work of art.",
    materials: ["18k Rose Gold", "Hand-painted Enamel", "Natural Ruby"],
    weight: "12g",
    images: ["🌹", "❤️", "✨"],
    inStock: true,
    sku: "VR-BR-005",
  },
  {
    id: 6,
    name: "Emerald Eternity Band",
    vendor: "Verdant Jewels",
    vendorId: 6,
    price: 4100,
    originalPrice: null,
    rating: 4.9,
    reviews: 156,
    isNew: false,
    isBestseller: true,
    icon: "💚",
    category: "rings",
    description: "A breathtaking eternity band featuring channel-set Colombian emeralds in 18k yellow gold. The perfect symbol of everlasting love.",
    materials: ["18k Yellow Gold", "AAA Colombian Emeralds"],
    weight: "5.8g",
    images: ["💚", "💍", "✨"],
    inStock: true,
    sku: "EE-RI-006",
  },
  {
    id: 7,
    name: "Art Deco Pendant",
    vendor: "Gatsby & Co",
    vendorId: 7,
    price: 2750,
    originalPrice: 3100,
    rating: 4.8,
    reviews: 73,
    isNew: true,
    isBestseller: false,
    icon: "🔶",
    category: "necklaces",
    description: "A geometric Art Deco pendant inspired by the roaring twenties. Features black onyx, diamonds, and white gold in a striking symmetric design.",
    materials: ["18k White Gold", "Black Onyx", "VS Diamonds"],
    weight: "15g",
    images: ["🔶", "⬛", "✨"],
    inStock: true,
    sku: "AD-PE-007",
  },
  {
    id: 8,
    name: "Platinum Chain Link",
    vendor: "Platinum House",
    vendorId: 8,
    price: 5600,
    originalPrice: null,
    rating: 4.9,
    reviews: 98,
    isNew: false,
    isBestseller: true,
    icon: "⛓️",
    category: "bracelets",
    description: "A substantial platinum chain link bracelet with a polished finish. Each link is individually crafted and hand-assembled for superior quality.",
    materials: ["950 Platinum"],
    weight: "62g",
    images: ["⛓️", "🔗", "✨"],
    inStock: true,
    sku: "PC-BR-008",
  },
]

export const vendors = [
  {
    id: 1,
    name: "Maison Étoile",
    location: "Paris, France",
    specialty: "Diamond Rings",
    rating: 4.9,
    products: 156,
    featured: true,
    icon: "🇫🇷",
    description: "Founded in 1892, Maison Étoile has been crafting exceptional diamond jewelry for over a century. Our Parisian atelier combines traditional French craftsmanship with contemporary design sensibilities.",
    established: 1892,
    artisans: 24,
    certifications: ["GIA Certified", "Responsible Jewellery Council"],
  },
  {
    id: 2,
    name: "Atelier Perle",
    location: "Tokyo, Japan",
    specialty: "Pearl Jewelry",
    rating: 4.8,
    products: 89,
    featured: true,
    icon: "🇯🇵",
    description: "Atelier Perle specializes in the finest Akoya and South Sea pearls, sourced directly from Japanese pearl farms. Each piece reflects the Japanese philosophy of perfection in simplicity.",
    established: 1956,
    artisans: 12,
    certifications: ["Japan Pearl Exporters Association", "ISO 9001"],
  },
  {
    id: 3,
    name: "Oro Fino",
    location: "Florence, Italy",
    specialty: "Gold Craftsmanship",
    rating: 4.9,
    products: 124,
    featured: false,
    icon: "🇮🇹",
    description: "From the heart of Florence, Oro Fino continues the Italian tradition of gold craftsmanship. Our master goldsmiths create pieces that honor centuries of Florentine artistry.",
    established: 1924,
    artisans: 18,
    certifications: ["Confindustria Federorafi", "Made in Italy Certified"],
  },
  {
    id: 4,
    name: "Azure Gems",
    location: "Jaipur, India",
    specialty: "Precious Gemstones",
    rating: 4.7,
    products: 203,
    featured: true,
    icon: "🇮🇳",
    description: "Azure Gems sources and cuts the world's finest colored gemstones from Jaipur, the pink city known for its gem trade. Our expertise spans sapphires, rubies, and emeralds.",
    established: 1978,
    artisans: 35,
    certifications: ["GJSCI Certified", "Kimberly Process"],
  },
  {
    id: 5,
    name: "Heritage House",
    location: "London, UK",
    specialty: "Vintage Pieces",
    rating: 4.8,
    products: 67,
    featured: false,
    icon: "🇬🇧",
    description: "Heritage House curates and restores exceptional vintage and antique jewelry from estates across Europe. Each piece comes with documented provenance and expert restoration.",
    established: 1965,
    artisans: 8,
    certifications: ["National Association of Jewellers", "BADA Member"],
  },
  {
    id: 6,
    name: "Verdant Jewels",
    location: "Bogotá, Colombia",
    specialty: "Emeralds",
    rating: 4.9,
    products: 98,
    featured: true,
    icon: "🇨🇴",
    description: "Verdant Jewels brings you the finest Colombian emeralds, ethically sourced from the legendary Muzo mines. Our emeralds are known for their exceptional color and clarity.",
    established: 1985,
    artisans: 15,
    certifications: ["FEDESMERALDAS", "Fair Trade Gems"],
  },
  {
    id: 7,
    name: "Gatsby & Co",
    location: "New York, USA",
    specialty: "Art Deco Design",
    rating: 4.8,
    products: 82,
    featured: false,
    icon: "🇺🇸",
    description: "Inspired by the glamour of the 1920s, Gatsby & Co creates modern interpretations of Art Deco jewelry. Bold geometric designs meet contemporary craftsmanship.",
    established: 2008,
    artisans: 10,
    certifications: ["JVC Member", "SCS Global Services"],
  },
  {
    id: 8,
    name: "Platinum House",
    location: "Antwerp, Belgium",
    specialty: "Platinum Jewelry",
    rating: 4.9,
    products: 76,
    featured: true,
    icon: "🇧🇪",
    description: "Platinum House specializes exclusively in platinum jewelry, crafted in the diamond capital of the world. Our pieces showcase the unparalleled beauty of this rare precious metal.",
    established: 1998,
    artisans: 14,
    certifications: ["AWDC Member", "Platinum Guild International"],
  },
]

export const categories = [
  {
    slug: "rings",
    name: "Rings",
    description: "Statement pieces for every occasion",
    longDescription: "From engagement rings to cocktail rings, our collection features the finest craftsmanship from artisans around the world. Each ring is a testament to timeless elegance and modern design.",
    itemCount: 156,
    icon: "💍",
  },
  {
    slug: "necklaces",
    name: "Necklaces",
    description: "Elegant chains and pendants",
    longDescription: "Discover an exquisite selection of necklaces ranging from delicate chains to statement pendants. Our curated collection features pearls, diamonds, and precious gemstones.",
    itemCount: 89,
    icon: "📿",
  },
  {
    slug: "bracelets",
    name: "Bracelets",
    description: "Timeless wrist adornments",
    longDescription: "Adorn your wrist with our beautiful collection of bracelets. From tennis bracelets to bold cuffs, find the perfect piece to complement your style.",
    itemCount: 72,
    icon: "⌚",
  },
  {
    slug: "earrings",
    name: "Earrings",
    description: "From studs to chandeliers",
    longDescription: "Express yourself with our stunning earring collection. Whether you prefer classic studs, elegant drops, or dramatic chandeliers, we have something for every taste.",
    itemCount: 124,
    icon: "✨",
  },
]

export type Product = typeof products[number]
export type Vendor = typeof vendors[number]
export type Category = typeof categories[number]
